spring:
  application:
    name: Observatorio Kings de Direitos Humanos do Vale do Itajai
  datasource:
    url: jdbc:mysql://localhost:3306/kings?useTimezone=true&serverTimezone=UTC
    username: root
    password: aluno

  
    name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time: -3
        format_sql: false
logger:
  root: WARN
  com.kings.okdhvi: WARN
logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: WARN
api:
  security:
    token:
      secret: ${JWT_SECRET:KINGS}